[env]
TERM = "xterm-256color"

[font]
size = 12
offset.x = 0  # For letter spacing (default: 0)
offset.y = 5  # For line spacing (default: 0)

[font.normal]
family = "Hack Nerd Font"

[shell]
args = ["-l", "-c", "tmux"]
program = "zsh"
